# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-20 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='searchCourtdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('case_number', models.CharField(max_length=100)),
                ('county', models.CharField(choices=[('hill', 'Hillsborough'), ('pine', 'Pinellas')], max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
